/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author flash
 */
import java.util.Random;
public class lab2p2_miguelmoran extends javax.swing.JFrame {

    /** Creates new form lab2p2_miguelmoran */
    public lab2p2_miguelmoran() {
        initComponents();
    }
    char[][] mapa = new char[5][5];
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    Random rng = new Random();
    int piedra = (mapa.length + mapa[0].length)/2;
    int madera = mapa.length*mapa[0].length/2;
    int carbon = mapa.length*mapa[0].length/4;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Input");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab2p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab2p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab2p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab2p2_miguelmoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab2p2_miguelmoran().setVisible(true);
            }
        });
    }
    
    public char[][] Generar_mapa(char[][] mapa){
        for (int i = 0; i < mapa.length; i++) {
            for (int j = 0; j < mapa[i].length; j++) {
                mapa[i][j] = ' ';
            }
        }
        for (int i = 0; i < madera; i++) {
            int x = rng.nextInt(mapa.length);
            int y = rng.nextInt(mapa[i].length);
            while(mapa[x][y] != ' '){
                x = rng.nextInt(mapa.length);
                y = rng.nextInt(mapa[i].length);
            }
            mapa[x][y] = 'M';
        }
        for (int i = 0; i < carbon; i++) {
            int x = rng.nextInt(mapa.length);
            int y = rng.nextInt(mapa[i].length);
            while(mapa[x][y] != ' '){
                x = rng.nextInt(mapa.length);
                y = rng.nextInt(mapa[i].length);
            }
            mapa[x][y] = 'C';
        }
        for (int i = 0; i < piedra; i++) {
            int x = rng.nextInt(mapa.length);
            int y = rng.nextInt(mapa[i].length);
            while(mapa[x][y] != ' '){
                x = rng.nextInt(mapa.length);
                y = rng.nextInt(mapa[i].length);
            }
            mapa[x][y] = 'P';
        }
        return mapa;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    // fila 4 columna 2
}
